# build environment

# pull official base image
FROM node:alpine as build
# set working directory
WORKDIR /ketcher_container
# add `/app/node_modules/.bin` to $PATH
ENV PATH /ketcher_container/node_modules/.bin:$PATH
# add app
COPY . .
RUN yarn
RUN yarn build

# production environment
# двухэтапная сборка
FROM nginx:alpine
COPY --from=build /ketcher_container/build /usr/share/nginx/html
# new
# COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]